"role: build_output_folders":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/community/roles/build_output_folders/*
          - ansible_collections/arista/community/roles/build_output_folders/**/*

"role: eos_validate_state":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/community/roles/eos_validate_state/*
          - ansible_collections/arista/community/roles/eos_validate_state/**/*

"role: dhcp_provisioner":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/community/roles/dhcp_provisioner/*
          - ansible_collections/arista/community/roles/dhcp_provisioner/**/*

"type: Python filters":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/community/plugins/filter/*.py

"type: Ansible roles":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/community/plugins/roles/**/*.yml
          - ansible_collections/arista/community/plugins/roles/**/*.j2

"state: Documentation role Updated":
  - changed-files:
      - any-glob-to-any-file:
          - 'ansible_collections/arista/community/roles/**/*.md'

"type: documentation":
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - CONTRIBUTE.md
          - ansible_collections/arista/community/*.md
          - ansible_collections/arista/community/docs/*
          - ansible_collections/arista/community/docs/**/*

"type: code quality":
  - changed-files:
      - any-glob-to-any-file:
          - .github/labeler.yml
          - .github/*
          - .github/**/*
          - development/docker-compose.yml
          - development/Makefile

"type: dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - development/requirements-dev.txt
          - development/requirements.txt
          - docs/requirements.txt

"state: CI Updated":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/molecule/*
          - ansible_collections/arista/avd/molecule/**/*
