changelog:
  exclude:
    labels:
      - 'rn: Test(build_output_folders)'
      - 'rn: CI(build_output_folders)'
      - 'rn: Test(dhcp_provisioner)'
      - 'rn: CI(dhcp_provisioner)'
      - 'rn: Test(eos_validate_state)'
      - 'rn: CI(eos_validate_state)'
      - 'rn: Test(plugins)'
      - 'rn: CI(plugins)'
      - 'rn: Test(requirements)'
      - 'rn: CI(requirements)'
      - 'rn: Test(containers)'
      - 'rn: CI(containers)'
      - 'rn: Test'
      - 'rn: CI'
  categories:
    - title: Breaking Changes
      labels:
        - 'rn: Feat(build_output_folders)!'
        - 'rn: Feat(dhcp_provisioner)!'
        - 'rn: Feat(eos_validate_state)!'
        - 'rn: Feat(plugins)!'
        - 'rn: Feat(requirements)!'
        - 'rn: Feat(containers)!'
        - 'rn: Fix(build_output_folders)!'
        - 'rn: Fix(dhcp_provisioner)!'
        - 'rn: Fix(eos_validate_state)!'
        - 'rn: Fix(plugins)!'
        - 'rn: Fix(requirements)!'
        - 'rn: Fix(containers)!'
        - 'rn: Cut(build_output_folders)!'
        - 'rn: Cut(dhcp_provisioner)!'
        - 'rn: Cut(eos_validate_state)!'
        - 'rn: Cut(plugins)!'
        - 'rn: Cut(requirements)!'
        - 'rn: Cut(containers)!'
        - 'rn: Revert(build_output_folders)!'
        - 'rn: Revert(dhcp_provisioner)!'
        - 'rn: Revert(eos_validate_state)!'
        - 'rn: Revert(plugins)!'
        - 'rn: Revert(requirements)!'
        - 'rn: Revert(containers)!'
        - 'rn: Refactor(build_output_folders)!'
        - 'rn: Refactor(dhcp_provisioner)!'
        - 'rn: Refactor(eos_validate_state)!'
        - 'rn: Refactor(plugins)!'
        - 'rn: Refactor(requirements)!'
        - 'rn: Refactor(containers)!'
        - 'rn: Bump(build_output_folders)!'
        - 'rn: Bump(dhcp_provisioner)!'
        - 'rn: Bump(eos_validate_state)!'
        - 'rn: Bump(plugins)!'
        - 'rn: Bump(requirements)!'
        - 'rn: Bump(containers)!'
        - 'rn: Feat!'
        - 'rn: Fix!'
        - 'rn: Cut!'
        - 'rn: Revert!'
        - 'rn: Refactor!'
        - 'rn: Bump!'
    - title: Fixed issues
      labels:
        - 'rn: Fix(build_output_folders)'
        - 'rn: Fix(dhcp_provisioner)'
        - 'rn: Fix(eos_validate_state)'
        - 'rn: Fix(plugins)'
        - 'rn: Fix(requirements)'
        - 'rn: Fix(containers)'
        - 'rn: Fix'
    - title: Documentation
      labels:
        - 'rn: Doc(build_output_folders)'
        - 'rn: Doc(dhcp_provisioner)'
        - 'rn: Doc(eos_validate_state)'
        - 'rn: Doc(plugins)'
        - 'rn: Doc(requirements)'
        - 'rn: Doc(containers)'
        - 'rn: Doc'
    - title: New features and enhancements
      labels:
        - 'rn: Feat(build_output_folders)'
        - 'rn: Feat(dhcp_provisioner)'
        - 'rn: Feat(eos_validate_state)'
        - 'rn: Feat(plugins)'
        - 'rn: Feat(requirements)'
        - 'rn: Feat(containers)'
        - 'rn: Feat'
    - title: Other Changes
      labels:
        - '*'
