sonar.projectKey=ansible-community-collection
sonar.organization=arista-netdevops-community

# Path to sources
sonar.sources=\
    ansible_collections/arista/community/plugins/,\

# Python version
sonar.python.version=\
    3.10,\
    3.11,\
    3.12,\
    3.13

sonar.python.coverage.reportPaths=\
    ansible_collections/arista/community/*coverage.xml

# Ignore issues on all compiled templates using regex match
sonar.issue.ignore.allfile=e1
sonar.issue.ignore.allfile.e1.fileRegexp=^name = .*\.j2\'$
